using Blackbird.Applications.Sdk.Utils.Sdk.DataSourceHandlers;

namespace Apps.LanguageWeaver.DataSourceHandlers.EnumHandlers;

public class LanguageDataHandler : EnumDataHandler
{
    protected override Dictionary<string, string> EnumValues => new()
    {
        { "afr", "Afrikaans" },
        { "alb", "Albanian" },
        { "amh", "Amharic" },
        { "ara", "Arabic" },
        { "arz", "Arabic (Arabizi)" },
        { "arm", "Armenian" },
        { "aze", "Azerbaijani" },
        { "baq", "Basque" },
        { "bel", "Belarusian" },
        { "ben", "Bengali" },
        { "bih", "Bihari" },
        { "bul", "Bulgarian" },
        { "bur", "Burmese" },
        { "cat", "Catalan" },
        { "ceb", "Cebuano" },
        { "chr", "Cherokee" },
        { "chi", "Chinese (Simplified)" },
        { "cht", "Chinese (Traditional)" },
        { "hrv", "Croatian" },
        { "cze", "Czech" },
        { "dan", "Danish" },
        { "fad", "Dari" },
        { "dut", "Dutch" },
        { "eng", "English" },
        { "est", "Estonian" },
        { "fin", "Finnish" },
        { "fra", "French" },
        { "frc", "French (Canadian)" },
        { "glg", "Galician" },
        { "lug", "Ganda" },
        { "geo", "Georgian" },
        { "ger", "German" },
        { "gre", "Greek" },
        { "guj", "Gujarati" },
        { "hau", "Hausa" },
        { "heb", "Hebrew" },
        { "hin", "Hindi" },
        { "hmn", "Hmong" },
        { "hun", "Hungarian" },
        { "ice", "Icelandic" },
        { "ind", "Indonesian" },
        { "iku", "Inuktitut" },
        { "gle", "Irish" },
        { "ita", "Italian" },
        { "jpn", "Japanese" },
        { "jav", "Javanese" },
        { "kan", "Kannada" },
        { "khm", "Khmer" },
        { "kin", "Kinyarwanda" },
        { "kor", "Korean" },
        { "kur", "Kurdish" },
        { "lav", "Latvian" },
        { "lif", "Limbu" },
        { "lit", "Lithuanian" },
        { "mac", "Macedonian" },
        { "may", "Malay" },
        { "mal", "Malayalam" },
        { "mlt", "Maltese" },
        { "mar", "Marathi" },
        { "nep", "Nepali" },
        { "nor", "Norwegian" },
        { "ori", "Oriya" },
        { "oss", "Ossetian" },
        { "pus", "Pashto" },
        { "per", "Persian" },
        { "pol", "Polish" },
        { "por", "Portuguese" },
        { "ptb", "Portuguese (Brazil)" },
        { "ptp", "Portuguese (Portugal)" },
        { "rum", "Romanian" },
        { "rus", "Russian" },
        { "srp", "Serbian" },
        { "slo", "Slovak" },
        { "slv", "Slovenian" },
        { "som", "Somali" },
        { "spa", "Spanish" },
        { "sun", "Sundanese" },
        { "swa", "Swahili" },
        { "swe", "Swedish" },
        { "syr", "Syriac" },
        { "tgl", "Tagalog" },
        { "tgk", "Tajik" },
        { "tam", "Tamil" },
        { "tel", "Telugu" },
        { "tha", "Thai" },
        { "tur", "Turkish" },
        { "ukr", "Ukrainian" },
        { "urd", "Urdu" },
        { "uzb", "Uzbek" },
        { "vie", "Vietnamese" },
        { "wel", "Welsh" },
        { "yid", "Yiddish" },
        { "unk", "UNKNOWN" }
    };
}